name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master # 여기에는 배포하고 싶은 브랜치를 지정하세요.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Node.js 버전을 18로 설정합니다.

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run pages:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
